const specData = [
  {
    "id": 1,
    "name": "硬件存储服务器机型六 (198T)",
    "cpu": "nan",
    "cpuModel": "nan",
    "memory": "nan",
    "mechanicalHardDrive": "198.0",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "块存储-SAN(DellNetWorker)"
  },
  {
    "id": 2,
    "name": "硬件存储服务器机型五  (71T)",
    "cpu": "nan",
    "cpuModel": "nan",
    "memory": "nan",
    "mechanicalHardDrive": "71.0",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "块存储-SAN(NBU)"
  },
  {
    "id": 3,
    "name": "硬件存储服务器机型四 (113.68T)",
    "cpu": "nan",
    "cpuModel": "nan",
    "memory": "nan",
    "mechanicalHardDrive": "113.68",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "块存储-SAN(A300)"
  },
  {
    "id": 4,
    "name": "硬件存储服务器机型三 (74.54T)",
    "cpu": "nan",
    "cpuModel": "nan",
    "memory": "nan",
    "mechanicalHardDrive": "74.54",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "块存储-SAN(NetApp8020)"
  },
  {
    "id": 5,
    "name": "硬件存储服务器机型二 (25.5T)",
    "cpu": "nan",
    "cpuModel": "nan",
    "memory": "nan",
    "mechanicalHardDrive": "25.5",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "块存储-SAN(NetApp2552)"
  },
  {
    "id": 6,
    "name": "硬件存储服务器机型一",
    "cpu": "24.0",
    "cpuModel": "nan",
    "memory": "0.0",
    "mechanicalHardDrive": "0.0",
    "solidStateDrive": "0.0",
    "videoMemory": "0.0",
    "gpuModel": "nan",
    "finopsCategory": "块存储-SAN(威联通服务器)"
  },
  {
    "id": 7,
    "name": "AI训练服务器机型四 (HUAWEI Kunpeng AT800 (Model 9000) A2 920 5250*4/32G*32/480Gssd*2/3.4Tssd*6/910B)",
    "cpu": "192.0",
    "cpuModel": "nan",
    "memory": "1024.0",
    "mechanicalHardDrive": "nan",
    "solidStateDrive": "21.0",
    "videoMemory": "64.0",
    "gpuModel": "nan",
    "finopsCategory": "NPU服务器-910B"
  },
  {
    "id": 8,
    "name": "AI训练服务器机型三 (96C/2048G/30T/H800*8)",
    "cpu": "96.0",
    "cpuModel": "nan",
    "memory": "2048.0",
    "mechanicalHardDrive": "30.0",
    "solidStateDrive": "nan",
    "videoMemory": "640.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-H800"
  },
  {
    "id": 9,
    "name": "AI训练服务器机型二 (96C/2048G/30T/H100*8)",
    "cpu": "96.0",
    "cpuModel": "nan",
    "memory": "2048.0",
    "mechanicalHardDrive": "30.0",
    "solidStateDrive": "nan",
    "videoMemory": "640.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-H100"
  },
  {
    "id": 10,
    "name": "AI训练服务器机型一 (64C/2048G/30T/A800*8)",
    "cpu": "64.0",
    "cpuModel": "nan",
    "memory": "2048.0",
    "mechanicalHardDrive": "30.0",
    "solidStateDrive": "nan",
    "videoMemory": "640.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-A800"
  },
  {
    "id": 11,
    "name": "AI推理服务器机型三 (HUAWEI Kunpeng AT800 4*920 5250*2/32G*8/480GSSD*2/ A300l*2/)",
    "cpu": "96.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "nan",
    "solidStateDrive": "0.9",
    "videoMemory": "96.0",
    "gpuModel": "nan",
    "finopsCategory": "NPU服务器-300I"
  },
  {
    "id": 12,
    "name": "AI推理服务器机型二 (32C/768G/23T/A40*2)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "768.0",
    "mechanicalHardDrive": "23.0",
    "solidStateDrive": "nan",
    "videoMemory": "96.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-A40"
  },
  {
    "id": 13,
    "name": "AI推理服务器机型一 (32C/512G/23T/A10*2)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "512.0",
    "mechanicalHardDrive": "23.0",
    "solidStateDrive": "nan",
    "videoMemory": "48.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-A10"
  },
  {
    "id": 14,
    "name": "图形渲染服务器机型十二 (96C/256G/2235 GB*7/T4*4)",
    "cpu": "96.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "16.0",
    "solidStateDrive": "nan",
    "videoMemory": "64.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-T4"
  },
  {
    "id": 15,
    "name": "图形渲染服务器机型十一 (16C/256G/1*1.92TSSD/4*2.4T SAS/A500*4)",
    "cpu": "16.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "9.6",
    "solidStateDrive": "1.92",
    "videoMemory": "96.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-A5000"
  },
  {
    "id": 16,
    "name": "图形渲染服务器机型十 (8/256G/1*1.92TSSD/4*2.4T SAS/P6000)",
    "cpu": "8.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "9.6",
    "solidStateDrive": "1.92",
    "videoMemory": "24.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-P6000"
  },
  {
    "id": 17,
    "name": "图形渲染服务器机型九 (8C/256G/1*1.92TSSD/4*2.4T SAS/P4000)",
    "cpu": "8.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "9.6",
    "solidStateDrive": "1.92",
    "videoMemory": "8.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-P4000"
  },
  {
    "id": 18,
    "name": "图形渲染服务器机型八 (10C/128G/1*1.92TSSD/1*4T/P2200 5G*1)",
    "cpu": "10.0",
    "cpuModel": "nan",
    "memory": "128.0",
    "mechanicalHardDrive": "4.0",
    "solidStateDrive": "1.92",
    "videoMemory": "5.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-P2200"
  },
  {
    "id": 19,
    "name": "图形渲染服务器机型七 (16C/256/1*1.92TSSD/4*2.4T SAS/RTX8000*1)",
    "cpu": "16.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "9.6",
    "solidStateDrive": "nan",
    "videoMemory": "48.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX8000"
  },
  {
    "id": 20,
    "name": "图形渲染服务器机型六 (128C/1024G/480GSSD*2+3.84T*3/RTX6000*4)",
    "cpu": "128.0",
    "cpuModel": "nan",
    "memory": "1024.0",
    "mechanicalHardDrive": "11.0",
    "solidStateDrive": "nan",
    "videoMemory": "192.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX6000"
  },
  {
    "id": 21,
    "name": "图形渲染服务器机型五 (32C/256G/3.8T SSD/RTX4090*2)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "nan",
    "solidStateDrive": "3.8",
    "videoMemory": "48.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX4090"
  },
  {
    "id": 22,
    "name": "图形渲染服务器机型四 (4C/256G/1*960GSSD/1*2T SATA/RTX4000*2)",
    "cpu": "4.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "2.0",
    "solidStateDrive": "0.0",
    "videoMemory": "16.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX4000"
  },
  {
    "id": 23,
    "name": "图形渲染服务器机型三 (16C/256G/8T SSD/RTX3090*2)",
    "cpu": "16.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "nan",
    "solidStateDrive": "8.0",
    "videoMemory": "48.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX3090"
  },
  {
    "id": 24,
    "name": "图形渲染服务器机型二 (28C/32G/500GSSD/RTX3080*1)",
    "cpu": "28.0",
    "cpuModel": "nan",
    "memory": "32.0",
    "mechanicalHardDrive": "0.5",
    "solidStateDrive": "nan",
    "videoMemory": "12.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX3080"
  },
  {
    "id": 25,
    "name": "图形渲染服务器机型一 (48C/64G/900G+4T*4+8T/RTX2080Ti*4)",
    "cpu": "48.0",
    "cpuModel": "nan",
    "memory": "64.0",
    "mechanicalHardDrive": "24.0",
    "solidStateDrive": "nan",
    "videoMemory": "11.0",
    "gpuModel": "nan",
    "finopsCategory": "GPU服务器-RTX2080TI"
  },
  {
    "id": 26,
    "name": "存储类服务器机型四 (64C/768G/72T+3.2T)",
    "cpu": "64.0",
    "cpuModel": "nan",
    "memory": "768.0",
    "mechanicalHardDrive": "75.2",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "大数据类超大存储"
  },
  {
    "id": 27,
    "name": "存储类服务器机型三 (32C/256G/34T SSD)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "nan",
    "solidStateDrive": "34.0",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "大数据类存储-高速IO"
  },
  {
    "id": 28,
    "name": "存储类服务器机型二 (32C/256G/72T)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "72.0",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "大数据类存储-机械大盘"
  },
  {
    "id": 29,
    "name": "存储类服务器机型一  (32C/256G/48T)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "48.0",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "大数据类存储-机械多盘"
  },
  {
    "id": 30,
    "name": "轻量级应用机型二 (龙芯3C/384G/8T)",
    "cpu": "3.0",
    "cpuModel": "nan",
    "memory": "384.0",
    "mechanicalHardDrive": "8.0",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "国产化服务器"
  },
  {
    "id": 31,
    "name": "轻量级应用机型一 (32C/256G/3.8T)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "0.0",
    "solidStateDrive": "3.8",
    "videoMemory": "0.0",
    "gpuModel": "nan",
    "finopsCategory": "小型单机应用"
  },
  {
    "id": 32,
    "name": "高性能服务器机型二 (48C/256G/15T)",
    "cpu": "48.0",
    "cpuModel": "nan",
    "memory": "256.0",
    "mechanicalHardDrive": "0.0",
    "solidStateDrive": "15.0",
    "videoMemory": "0.0",
    "gpuModel": "nan",
    "finopsCategory": "高速编译型应用"
  },
  {
    "id": 33,
    "name": "高性能服务器机型一 (32/512G/11T SSD)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "512.0",
    "mechanicalHardDrive": "0.0",
    "solidStateDrive": "11.0",
    "videoMemory": "0.0",
    "gpuModel": "nan",
    "finopsCategory": "高性能容器应用"
  },
  {
    "id": 34,
    "name": "标准通用服务器机型二 (32C/512G/24T)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "512.0",
    "mechanicalHardDrive": "24.0",
    "solidStateDrive": "nan",
    "videoMemory": "nan",
    "gpuModel": "nan",
    "finopsCategory": "标准通用服务器-虚拟化类应用"
  },
  {
    "id": 35,
    "name": "标准通用服务器机型一 (32C/384G/11T)",
    "cpu": "32.0",
    "cpuModel": "nan",
    "memory": "384.0",
    "mechanicalHardDrive": "0.0",
    "solidStateDrive": "11.0",
    "videoMemory": "0.0",
    "gpuModel": "nan",
    "finopsCategory": "标准通用服务器-容器应用"
  }
];