spring:
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.finops.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.finops: debug
